apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ['sh', '-c', 'cat /data/data.txt']
    volumeMounts:
      - mountPath: /data
        name: host-data
  volumes:
    - name: host-data
      hostPath:
        path: /etc/hostPath
        type: Directory